### PR TITLE
Fixes webpack warnings

### PR DESCRIPTION
**Pull request by Unesdala**

### CODE REVIEW

**Review by JoshuaVSherman — COMMENTED** [review]
@Unesdala in this branch is that were you are facing the reversing of text inside of the editor?
if that is the case, then i'm not going to approve/merge this branch until that gets fixed, please let me know, thank you

**Review by JoshuaVSherman — CHANGES_REQUESTED** [review]
I got this when installing locally your branch, so it is not correct it would seem, 
image

**Comment by Unesdala** [comment]
@JoshuaVSherman - Yeah, it's looking at your .env file, which I'm guessing is set to development. By default, yarn start build runs webpack.production. Which would have the NODE_ENV be wrong, since it's looking for production.

We could split the webpack config into dev/production/common/config, and have it build based on that, and then have two .env files (For production/development), albeit, that would require a fair bit of rewriting code.

That, or if you know how to get nps scripts to run webpack.development when we're doing local work, and have yarn start build be based on that (Like build:dev, or something like that), that would solve the issue for that.

Just changing the build scripts would be faster. The way we have webpack setup right now should be changing it up based on whether it's running a build for development or production as is - it's just that nps is defaulting to production when building. And I've no clue how to set it up to be able to pass in for development vs production.

**Comment by JoshuaVSherman** [comment]
@Unesdala are you going to fix this? No we don't use mutiple .env files, that is incorrect, you need to update the build scripts to work with the newer webpack config then, please do that or let me know if you are not able to fix and I will do this instead, thank you

**Comment by Unesdala** [comment]
@JoshuaVSherman I tinkered around with it, but couldn't get it working quite right. If you get some time can you finish it up?

**Comment by JoshuaVSherman** [comment]
@Unesdala since this is not my area of expertise, I would estimate it would take me a good 4 hours to figure out and fix. I am not available right now to work on this, so I am going to move it to the backlog and you can work on something else if you wish. I would also recommend that you post on Stackoverflow and use the Gitter developer chat to find an expert on webpack who could help you (which is what I would probably do if I were working on this ticket)

**Review by JoshuaVSherman — APPROVED** [review]

**Pull request merged**
